apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod-with-sync
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  - image: openweb/git-sync:0.0.1
    name: git-sync
    env:
      - name: GIT_SYNC_REPO
        value: https://github.com/gbengataylor/kubia-website-example.git
      - name: GIT_SYNC_DEST
        value: "/git"
      - name: GIT_SYNC_BRANCH
        value: master
      - name: GIT_SYNC_WAIT
        value: "5"     
      - name: GIT_SYNC_REV
        value: FETCH_HEAD
    volumeMounts:
    - name: html
      mountPath: /git
  volumes:
  - name: html
    gitRepo:
      repository: https://github.com/gbengataylor/kubia-website-example.git
      revision: master
      #this will copy all the contents in . directory rather than kubia-website-example dir
      directory: . #this will copy all the contents in root directory of the volume rather than kubia-website-example subdirectory

