apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
#specifying a node port is not necessary. k8s can randomly assign it
#this node port will be reserved on all nodes in the cluster
    nodePort: 30123
  selector:
    app: kubia

